import 'package:pokedex/models/egg.dart';

class JSONEggs {
  static List<Egg> eggs() {
    return [
      Egg(number: 4, name: "Charmander", eggDistance: 2),
      Egg(number: 7, name: "Squirtle", eggDistance: 2),
      Egg(number: 10, name: "Caterpie", eggDistance: 2),
      Egg(number: 13, name: "Weedle", eggDistance: 2),
      Egg(number: 16, name: "Pidgey", eggDistance: 2),
      Egg(number: 19, name: "Rattata", eggDistance: 2),
      Egg(number: 21, name: "Spearow", eggDistance: 2),
      Egg(number: 25, name: "Pikachu", eggDistance: 2),
      Egg(number: 35, name: "Clefairy", eggDistance: 2),
      Egg(number: 39, name: "Jigglypuff", eggDistance: 2),
      Egg(number: 41, name: "Zubat", eggDistance: 2),
      Egg(number: 74, name: "Geodude", eggDistance: 2),
      Egg(number: 129, name: "Magikarp", eggDistance: 2),
      Egg(number: 23, name: "Ekans", eggDistance: 5),
      Egg(number: 27, name: "Sandshrew", eggDistance: 5),
      Egg(number: 29, name: "Nidoran♀", eggDistance: 5),
      Egg(number: 32, name: "Nidoran♂", eggDistance: 5),
      Egg(number: 37, name: "Vulpix", eggDistance: 5),
      Egg(number: 43, name: "Oddish", eggDistance: 5),
      Egg(number: 46, name: "Paras", eggDistance: 5),
      Egg(number: 48, name: "Venonat", eggDistance: 5),
      Egg(number: 50, name: "Diglett", eggDistance: 5),
      Egg(number: 52, name: "Meowth", eggDistance: 5),
      Egg(number: 54, name: "Psyduck", eggDistance: 5),
      Egg(number: 56, name: "Mankey", eggDistance: 5),
      Egg(number: 58, name: "Growlithe", eggDistance: 5),
      Egg(number: 60, name: "Poliwag", eggDistance: 5),
      Egg(number: 63, name: "Abra", eggDistance: 5),
      Egg(number: 66, name: "Machop", eggDistance: 5),
      Egg(number: 69, name: "Bellsprout", eggDistance: 5),
      Egg(number: 72, name: "Tentacool", eggDistance: 5),
      Egg(number: 77, name: "Ponyta", eggDistance: 5),
      Egg(number: 79, name: "Slowpoke", eggDistance: 5),
      Egg(number: 81, name: "Magnemite", eggDistance: 5),
      Egg(number: 83, name: "Farfetch\'", eggDistance: 5),
      Egg(number: 84, name: "Doduo", eggDistance: 5),
      Egg(number: 86, name: "Seel", eggDistance: 5),
      Egg(number: 88, name: "Grimer", eggDistance: 5),
      Egg(number: 90, name: "Shellder", eggDistance: 5),
      Egg(number: 92, name: "Gastly", eggDistance: 5),
      Egg(number: 96, name: "Drowzee", eggDistance: 5),
      Egg(number: 98, name: "Krabby", eggDistance: 5),
      Egg(number: 100, name: "Voltorb", eggDistance: 5),
      Egg(number: 102, name: "Exeggcute", eggDistance: 5),
      Egg(number: 104, name: "Cubone", eggDistance: 5),
      Egg(number: 108, name: "Lickitung", eggDistance: 5),
      Egg(number: 109, name: "Koffing", eggDistance: 5),
      Egg(number: 111, name: "Rhyhorn", eggDistance: 5),
      Egg(number: 114, name: "Tangela", eggDistance: 5),
      Egg(number: 115, name: "Kangaskhan", eggDistance: 5),
      Egg(number: 116, name: "Horsea", eggDistance: 5),
      Egg(number: 118, name: "Goldeen", eggDistance: 5),
      Egg(number: 120, name: "Staryu", eggDistance: 5),
      Egg(number: 128, name: "Tauros", eggDistance: 5),
      Egg(number: 137, name: "Porygon", eggDistance: 5),
      Egg(number: 95, name: "Onix", eggDistance: 10),
      Egg(number: 106, name: "Hitmonlee", eggDistance: 10),
      Egg(number: 107, name: "Hitmonchan", eggDistance: 10),
      Egg(number: 113, name: "Chansey", eggDistance: 10),
      Egg(number: 122, name: "Mr.Mime", eggDistance: 10),
      Egg(number: 123, name: "Scyther", eggDistance: 10),
      Egg(number: 124, name: "Jynx", eggDistance: 10),
      Egg(number: 125, name: "Electabuzz", eggDistance: 10),
      Egg(number: 126, name: "Magmar", eggDistance: 10),
      Egg(number: 127, name: "Pinsir", eggDistance: 10),
      Egg(number: 131, name: "Lapras", eggDistance: 10),
      Egg(number: 133, name: "Eevee", eggDistance: 10),
      Egg(number: 138, name: "Omanyte", eggDistance: 10),
      Egg(number: 140, name: "Kabuto", eggDistance: 10),
      Egg(number: 142, name: "Aerodactyl", eggDistance: 10),
      Egg(number: 143, name: "Snorlax", eggDistance: 10),
      Egg(number: 147, name: "Dratini", eggDistance: 10),
    ];
  }
}
